"""initial_schema

Revision ID: 7370293b15fe
Revises: 
Create Date: 2026-08-02 12:42:39.678230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7370293b15fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('rego', sa.String(length=20), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=120), nullable=True),
    sa.Column('transmission', sa.String(length=60), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_rego'), 'vehicles', ['rego'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('fuel_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('fill_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('litres', sa.Float(), nullable=False),
    sa.Column('price_per_litre', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_full_tank', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('l_per_100km', sa.Float(), nullable=True),
    sa.Column('cost_per_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_logs_fill_date'), 'fuel_logs', ['fill_date'], unique=False)
    op.create_index(op.f('ix_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_table('modifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_keys', sa.Text(), nullable=True),
    sa.Column('ai_impact', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifications_vehicle_id'), 'modifications', ['vehicle_id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('ai_reorder_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_sku'), 'parts', ['sku'], unique=False)
    op.create_index(op.f('ix_parts_vehicle_id'), 'parts', ['vehicle_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('extracted', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('invoice_date', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_vehicle_id'), 'receipts', ['vehicle_id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workshop', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_prediction', sa.Text(), nullable=True),
    sa.Column('next_due_km', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_service_date'), 'service_records', ['service_date'], unique=False)
    op.create_index(op.f('ix_service_records_vehicle_id'), 'service_records', ['vehicle_id'], unique=False)
    op.create_table('valuation_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('factors', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_snapshots_vehicle_id'), 'valuation_snapshots', ['vehicle_id'], unique=False)
    op.create_table('vehicle_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_events_event_type'), 'vehicle_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_vehicle_events_occurred_on'), 'vehicle_events', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_vehicle_events_vehicle_id'), 'vehicle_events', ['vehicle_id'], unique=False)
    op.create_table('diagnostics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('parts_needed', sa.Text(), nullable=True),
    sa.Column('added_to_service', sa.Boolean(), nullable=False),
    sa.Column('linked_service_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_service_id'], ['service_records.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_vehicle_id'), 'diagnostics', ['vehicle_id'], unique=False)
    op.create_table('extracted_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('applied_to_service', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_items_receipt_id'), 'extracted_items', ['receipt_id'], unique=False)
    op.create_table('part_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_movements_part_id'), 'part_movements', ['part_id'], unique=False)
    op.create_table('service_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('labour_hours', sa.Float(), nullable=True),
    sa.Column('labour_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_items_service_id'), 'service_items', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_items_service_id'), table_name='service_items')
    op.drop_table('service_items')
    op.drop_index(op.f('ix_part_movements_part_id'), table_name='part_movements')
    op.drop_table('part_movements')
    op.drop_index(op.f('ix_extracted_items_receipt_id'), table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_diagnostics_vehicle_id'), table_name='diagnostics')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_vehicle_events_vehicle_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_occurred_on'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_event_type'), table_name='vehicle_events')
    op.drop_table('vehicle_events')
    op.drop_index(op.f('ix_valuation_snapshots_vehicle_id'), table_name='valuation_snapshots')
    op.drop_table('valuation_snapshots')
    op.drop_index(op.f('ix_service_records_vehicle_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_service_date'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_receipts_vehicle_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_parts_vehicle_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_sku'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_modifications_vehicle_id'), table_name='modifications')
    op.drop_table('modifications')
    op.drop_index(op.f('ix_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_fill_date'), table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_rego'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
