"""AUT-3614: Tire inventory and usage tracking tables.

Revision ID: aut3614_tire_inventory
Revises: z2a3b4c5d6e7
Create Date: 2026-09-20 15:20:31.458349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "aut3614_tire_inventory"
down_revision: Union[str, None] = "z2a3b4c5d6e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

COMPOUND_LIFE_KM = {
    "street": 40000,
    "all_season": 50000,
    "performance": 25000,
    "track": 8000,
    "racing": 4000,
    "rally": 6000,
    "wet": 10000,
    "drag": 2000,
}

COMPOUND_NEW_TREAD_MM = {
    "street": 8.0,
    "all_season": 8.5,
    "performance": 7.0,
    "track": 5.0,
    "wet": 8.0,
    "racing": 4.0,
    "rally": 6.0,
    "drag": 3.0,
}


def _upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tire_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("size", sa.String(length=30), nullable=False),
        sa.Column("compound", sa.String(length=30), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_cost", sa.Float(), nullable=True),
        sa.Column("new_tread_mm", sa.Float(), nullable=False, server_default="8.0"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="active"),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tire_sets_vehicle_id"), "tire_sets", ["vehicle_id"], unique=False)
    op.create_index(op.f("ix_tire_sets_compound"), "tire_sets", ["compound"], unique=False)

    op.create_table(
        "tire_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tire_set_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("track_name", sa.String(length=200), nullable=True),
        sa.Column("session_type", sa.String(length=20), nullable=False, server_default="street"),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("weather", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tire_set_id"], ["tire_sets.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tire_sessions_tire_set_id"), "tire_sessions", ["tire_set_id"], unique=False)
    op.create_index(op.f("ix_tire_sessions_session_date"), "tire_sessions", ["session_date"], unique=False)

    op.create_table(
        "tire_tread_readings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tire_set_id", sa.String(length=36), nullable=False),
        sa.Column("reading_date", sa.Date(), nullable=False),
        sa.Column("depth_mm", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tire_set_id"], ["tire_sets.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tire_tread_readings_tire_set_id"), "tire_tread_readings", ["tire_set_id"], unique=False)
    op.create_index(op.f("ix_tire_tread_readings_reading_date"), "tire_tread_readings", ["reading_date"], unique=False)

    # Also create compound lookup indexes (reference data)
    op.create_table(
        "tire_compound_lookups",
        sa.Column("compound", sa.String(length=30), nullable=False),
        sa.Column("new_tread_mm", sa.Float(), nullable=False),
        sa.Column("life_km", sa.Integer(), nullable=False),
        sa.Column("min_tread_mm", sa.Float(), nullable=False),
        sa.Column("heat_cycle_penalty", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("compound"),
    )
    for compound, life_km in COMPOUND_LIFE_KM.items():
        new_mm = COMPOUND_NEW_TREAD_MM.get(compound, 8.0)
        op.execute(
            sa.insert("tire_compound_lookups").values(
                compound=compound,
                new_tread_mm=new_mm,
                life_km=life_km,
                min_tread_mm=1.6,
                heat_cycle_penalty=0.03,
            )
        )
    # ### end Alembic commands ###


def _downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tire_compound_lookups")
    op.drop_index(op.f("ix_tire_tread_readings_reading_date"), table_name="tire_tread_readings")
    op.drop_index(op.f("ix_tire_tread_readings_tire_set_id"), table_name="tire_tread_readings")
    op.drop_table("tire_tread_readings")
    op.drop_index(op.f("ix_tire_sessions_session_date"), table_name="tire_sessions")
    op.drop_index(op.f("ix_tire_sessions_tire_set_id"), table_name="tire_sessions")
    op.drop_table("tire_sessions")
    op.drop_index(op.f("ix_tire_sets_compound"), table_name="tire_sets")
    op.drop_index(op.f("ix_tire_sets_vehicle_id"), table_name="tire_sets")
    op.drop_table("tire_sets")
    # ### end Alembic commands ###


def upgrade() -> None:
    _upgrade()


def downgrade() -> None:
    _downgrade()
